# Generated by Django 4.1.3 on 2023-02-13 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(max_length=7)),
                ('nombre', models.CharField(max_length=24)),
                ('apellido', models.CharField(max_length=24)),
                ('domicilio', models.CharField(max_length=24)),
                ('localidad', models.CharField(max_length=24, verbose_name='Localidad')),
                ('telefono_fijo', models.CharField(max_length=14, verbose_name='Telefono Fijo')),
                ('telefono_movil', models.CharField(max_length=14, verbose_name='Telefono Celular')),
                ('email', models.EmailField(max_length=254, verbose_name='E mail')),
                ('especialidad', models.CharField(choices=[('Otorrinolaringologia', 'Otorrinolaringologia'), ('Nutricion', 'Nutricion'), ('Psicologia', 'Psicologia'), ('Fonoaudiologia', 'Fonoaudiologia'), ('Odontologia', 'Odontologia'), ('Clinica', 'Clinica'), ('Ginecologia', 'Ginecologia'), ('Pediatria', 'Pediatria')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(max_length=7)),
                ('nombre', models.CharField(max_length=24)),
                ('apellido', models.CharField(max_length=24)),
                ('domicilio', models.CharField(max_length=24)),
                ('localidad', models.CharField(max_length=24, verbose_name='Localidad')),
                ('telefono_fijo', models.CharField(max_length=14, verbose_name='Telefono Fijo')),
                ('telefono_movil', models.CharField(max_length=14, verbose_name='Telefono Celular')),
                ('email', models.EmailField(max_length=254, verbose_name='E mail')),
                ('obra_social', models.CharField(max_length=24)),
                ('numero_afiliado_obra_social', models.CharField(max_length=24, verbose_name='Numero de afiliado')),
            ],
        ),
        migrations.CreateModel(
            name='turnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha Turno')),
                ('horario', models.TimeField(verbose_name='Horario Turno')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_medicadmin.medicos')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_medicadmin.pacientes')),
            ],
        ),
    ]
