# Generated by Django 4.1.3 on 2023-02-13 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_medicadmin', '0002_alter_medicos_dni_alter_pacientes_dni'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='medicos',
            new_name='medico',
        ),
        migrations.RenameModel(
            old_name='pacientes',
            new_name='paciente',
        ),
        migrations.RenameModel(
            old_name='turnos',
            new_name='turno',
        ),
    ]
