# Generated by Django 4.1.3 on 2023-02-21 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_medicadmin', '0003_rename_medicos_medico_rename_pacientes_paciente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='numero_telefonico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='tarjeta_contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domicilio_calle', models.CharField(max_length=20)),
                ('domicilio_numero', models.CharField(max_length=5)),
                ('domicilio_piso', models.CharField(max_length=2)),
                ('domicilio_depto', models.CharField(max_length=2)),
                ('numero_telefonico_1', models.CharField(max_length=14)),
                ('numero_telefonico_2', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='medico',
            name='dni',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='obra_social',
            field=models.CharField(choices=[('OSDE', 'OSDE'), ('GALENO', 'GALENO'), ('IOMA', 'IOMA'), ('CEDIMEC', 'CEDIMEC'), ('OSFE', 'OSFE'), ('OSECACO', 'OSECACO'), ('MEDIFES', 'MEDIFES'), ('Otra', 'Otra')], max_length=24),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tarjeta_de_contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_medicadmin.tarjeta_contacto'),
        ),
    ]
