# Generated by Django 4.1.3 on 2023-02-21 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_medicadmin', '0004_numero_telefonico_tarjeta_contacto_alter_medico_dni_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tarjeta_obra_social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obra_social', models.CharField(choices=[('OSDE', 'OSDE'), ('GALENO', 'GALENO'), ('IOMA', 'IOMA'), ('CEDIMEC', 'CEDIMEC'), ('OSFE', 'OSFE'), ('OSECACO', 'OSECACO'), ('MEDIFES', 'MEDIFES'), ('Otra', 'Otra')], max_length=24)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='tarjeta_obra_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_medicadmin.tarjeta_obra_social'),
        ),
    ]
