# Generated by Django 4.1.3 on 2023-02-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_medicadmin', '0005_tarjeta_obra_social_paciente_tarjeta_obra_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta_obra_social',
            name='num_afiliado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
