# Generated by Django 4.1.3 on 2023-02-21 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_medicadmin', '0008_tarjeta_contacto_medico_tarjeta_contacto_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta_contacto',
            name='medico',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_medicadmin.medico'),
        ),
        migrations.AlterField(
            model_name='tarjeta_contacto',
            name='paciente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_medicadmin.paciente'),
        ),
    ]
