# Generated by Django 4.1.3 on 2023-02-21 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_medicadmin', '0010_remove_paciente_localidad_tarjeta_contacto_localidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='numero_afiliado_obra_social',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='obra_social',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telefono_fijo',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telefono_movil',
        ),
    ]
