# Generated by Django 4.1.3 on 2023-02-21 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_medicadmin', '0011_remove_paciente_domicilio_remove_paciente_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='email',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='telefono_fijo',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='telefono_movil',
        ),
    ]
