# Generated by Django 4.1.3 on 2023-02-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_medicadmin', '0012_remove_medico_domicilio_remove_medico_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='numero_telefonico',
        ),
        migrations.AlterField(
            model_name='tarjeta_obra_social',
            name='obra_social',
            field=models.CharField(choices=[('OSDE', 'OSDE'), ('GALENO', 'GALENO'), ('IOMA', 'IOMA'), ('CEDIMEC', 'CEDIMEC'), ('OSFE', 'OSFE'), ('OSECACO', 'OSECACO'), ('MEDIFES', 'MEDIFES'), ('Otra', 'Otra'), ('S/N', 'S/N')], default='S/N', max_length=24),
        ),
    ]
