# Generated by Django 4.1.3 on 2023-02-24 18:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_medicadmin', '0021_alter_aviso_llegada_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aviso_llegada',
            name='medico',
        ),
        migrations.AlterField(
            model_name='aviso_llegada',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 2, 24, 15, 36, 43, 27304), verbose_name='Fecha Anunciado'),
        ),
        migrations.AlterField(
            model_name='aviso_llegada',
            name='horario',
            field=models.TimeField(default=datetime.datetime(2023, 2, 24, 15, 36, 43, 27304), verbose_name='Horario Anunciado'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 2, 24, 15, 36, 43, 26304), verbose_name='Fecha Turno'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='horario',
            field=models.TimeField(default=datetime.datetime(2023, 2, 24, 15, 36, 43, 26304), verbose_name='Horario Turno'),
        ),
        migrations.CreateModel(
            name='novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime(2023, 2, 24, 15, 36, 43, 27304), verbose_name='Fecha Anunciado')),
                ('horario', models.TimeField(default=datetime.datetime(2023, 2, 24, 15, 36, 43, 27304), verbose_name='Horario Anunciado')),
                ('titulo', models.CharField(max_length=30)),
                ('emisor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
