# Generated by Django 4.1.3 on 2023-02-24 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_medicadmin', '0022_remove_aviso_llegada_medico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='post_novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('image', models.ImageField(upload_to='imagenes', verbose_name='Imagen')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Novedad',
                'verbose_name_plural': 'Novedades',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AlterField(
            model_name='aviso_llegada',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 2, 24, 16, 14, 15, 24524), verbose_name='Fecha Anunciado'),
        ),
        migrations.AlterField(
            model_name='aviso_llegada',
            name='horario',
            field=models.TimeField(default=datetime.datetime(2023, 2, 24, 16, 14, 15, 24524), verbose_name='Horario Anunciado'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 2, 24, 16, 14, 15, 23526), verbose_name='Fecha Turno'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='horario',
            field=models.TimeField(default=datetime.datetime(2023, 2, 24, 16, 14, 15, 23526), verbose_name='Horario Turno'),
        ),
        migrations.DeleteModel(
            name='novedad',
        ),
    ]
