# Generated by Django 4.1.3 on 2023-02-24 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_medicadmin', '0024_rename_content_post_novedad_contenido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso_llegada',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha Anunciado'),
        ),
        migrations.AlterField(
            model_name='aviso_llegada',
            name='horario',
            field=models.TimeField(auto_now_add=True, verbose_name='Horario Anunciado'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 2, 24, 17, 29, 20, 562248), verbose_name='Fecha Turno'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='horario',
            field=models.TimeField(default=datetime.datetime(2023, 2, 24, 17, 29, 20, 562248), verbose_name='Horario Turno'),
        ),
    ]
