# Generated by Django 4.1.3 on 2023-03-07 16:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_medicadmin', '0025_alter_aviso_llegada_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_novedad',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 3, 7, 13, 43, 20, 403285), verbose_name='Fecha Turno'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='horario',
            field=models.TimeField(default=datetime.datetime(2023, 3, 7, 13, 43, 20, 403285), verbose_name='Horario Turno'),
        ),
    ]
