# Generated by Django 4.1.3 on 2023-02-23 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_sesiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='perfil_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('dni', models.CharField(max_length=10)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('categoria', models.CharField(choices=[('MEDICO', 'MEDICO'), ('SECRETARIA', 'SECRETARIA'), ('ADMIN', 'ADMIN')], max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
