# Generated by Django 4.1.3 on 2023-02-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sesiones', '0002_perfil_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='med1.jpg', null=True, upload_to='avatares'),
        ),
    ]
