# Generated by Django 4.1.3 on 2023-02-24 02:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_sesiones', '0004_novedades'),
    ]

    operations = [
        migrations.CreateModel(
            name='mensaje_institucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime(2023, 2, 23, 23, 29, 57, 483877), verbose_name='Fecha Anunciado')),
                ('horario', models.TimeField(default=datetime.datetime(2023, 2, 23, 23, 29, 57, 483877), verbose_name='Horario Anunciado')),
                ('autor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='novedades',
            name='autor',
        ),
        migrations.DeleteModel(
            name='avatar',
        ),
        migrations.DeleteModel(
            name='novedades',
        ),
    ]
