# Generated by Django 4.1.3 on 2023-02-24 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sesiones', '0006_mensaje_institucional_mensaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje_institucional',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 2, 23, 23, 44, 40, 211306), verbose_name='Fecha Anunciado'),
        ),
        migrations.AlterField(
            model_name='mensaje_institucional',
            name='horario',
            field=models.TimeField(default=datetime.datetime(2023, 2, 23, 23, 44, 40, 211306), verbose_name='Horario Anunciado'),
        ),
    ]
