# Generated by Django 4.1.3 on 2023-02-24 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sesiones', '0008_alter_mensaje_institucional_autor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje_institucional',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='mensaje_institucional',
            name='horario',
        ),
    ]
