# Generated by Django 4.1.3 on 2023-02-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sesiones', '0009_remove_mensaje_institucional_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
